Database documentation
hawkkiller/sizzle_starter_docs pull request #1
Opened 2023-11-14 22:14 UTC by BorisKest

Added basic documentation for the database and Drift library.

2023-11-20 11:41 UTC, hawkkiller requested changes

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +[Drift library](#what-is-drift).
Our projects mainly focus on interacting with the backend through message exchange. At times, we need to store data for caching or similar reasons. While there's a wide range of options available, various factors must be considered carefully. After evaluating numerous libraries, we've selected [SQLite](#sqlite) as our preferred choice.

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +## Why SQLite?
## SQLite

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +SQLite is selected for data processing due:
SQLite is a compact, relational database management system designed for efficient disk-based operations. It's widely utilized in a variety of settings, including desktop and mobile applications, IoT devices, and web environments. With its deployment in millions of production applications globally, SQLite's robustness is further reinforced by an extensive suite of over one billion test cases, ensuring a high level of reliability and minimal error incidence.

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +  systems.
Not needed

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +## What is Drift?
## Drift

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +    BlobColumn get receiptImage => blob().nullable()();
It is considered a bad practise to store images in databases as BLOB. It is preferred to store links in fs.

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +### Data source and repositorie
This is not needed

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +[here](https://drift.simonbinder.eu/docs/dart-api/select/).
To my mind, there is no need to tell about all the features of Drift. Leave only inserts, updates and selects (but make select with various modificators such as limit and ordering)

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +#### Whats the deal with package?
### Local package

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +future, new fields or tables may emerge, and for such changes, a migration tool exists.
Predicting initial data requirements for a table can be complex, as data needs often evolve, requiring new fields or tables. Migration tools are crucial for adapting the database structure to these changing requirements, ensuring flexibility and robustness.

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +functionality across various devices.
Remove

2023-11-20 11:41 UTC, hawkkiller commented on src/content/docs/essentials/database.mdx
> +reduces dependencies, and enhances maintainability.
The database schema is moved to a different package called `database`. There are a few reasons for this: the schema itself doesn't change frequently, so there is no need to spend time during the codegen. Moreover, it improves project organization as everything related to database is grouped in different package. This package also provides executors logic.

**Executor** is a component tasked with managing and executing database queries. To guarantee optimal performance and compatibility, Drift utilizes different executors tailored to each platform. These platform-specific executors are engineered to align with the unique nuances and requirements of their respective platforms, ensuring efficient and seamless database interactions across a range of devices.

2023-11-21 11:11 UTC, BorisKest reviewed
Added requested changes.

2023-12-06 17:19 UTC, merged